[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
position = 'at'
match_indent = true
pattern = '''
G.shop_vouchers = CardArea(
    G.hand.T.x+0,
    G.hand.T.y+G.ROOM.T.y + 9,
    2.1*G.CARD_W,
    1.05*G.CARD_H,
    {card_limit = 1, type = 'shop', highlight_limit = 1})

G.shop_booster = CardArea(
    G.hand.T.x+0,
    G.hand.T.y+G.ROOM.T.y + 9,
    2.4*G.CARD_W,
    1.15*G.CARD_H,
    {card_limit = 2, type = 'shop', highlight_limit = 1, card_w = 1.27*G.CARD_W})
'''
payload = '''
G.shop_vouchers = CardArea(
    G.hand.T.x+0,
    G.hand.T.y+G.ROOM.T.y + 9,
    G.GAME.mm_banner_slot and 1.5*G.CARD_W or 2.1*G.CARD_W,
    1.05*G.CARD_H,
    {card_limit = 1, type = 'shop', highlight_limit = 1}
)

G.shop_wuwa_banner = CardArea(
    G.hand.T.x+0,
    G.hand.T.y+G.ROOM.T.y + 9,
    0.95*G.CARD_W,
    1.15*G.CARD_H,
    {
        card_limit = 1,
        type = 'shop',
        highlight_limit = 1,
        card_w = 1.2*G.CARD_W
    }
)

G.shop_booster = CardArea(
    G.hand.T.x+0,
    G.hand.T.y+G.ROOM.T.y + 9,
    G.GAME.mm_banner_slot and 2.0*G.CARD_W or 2.4*G.CARD_W,
    1.15*G.CARD_H,
    {
        card_limit = 2,
        type = 'shop',
        highlight_limit = 1,
        card_w = 1.22*G.CARD_W
    }
)
'''
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
position = 'before'
match_indent = true
pattern = '''
{n=G.UIT.C, config={align = "cm", padding = 0.15, r=0.2, colour = G.C.L_BLACK, emboss = 0.05}, nodes={
    {n=G.UIT.O, config={object = G.shop_booster}},
}},
'''
payload = '''
G.GAME.mm_banner_slot and {
    n=G.UIT.C,
    config={
        align="cm",
        padding=0.15,
        r=0.2,
        colour=HEX("FFC000"),
        emboss=0.05
    },
    nodes={
        {
            n=G.UIT.C,
            config={
                align="cm",
                padding=0.2,
                r=0.2,
                colour=HEX("374244"),
                maxh = G.shop_wuwa_banner.T.h + 0.4
            },
            nodes={
                {
                    n=G.UIT.O,
                    config={object = G.shop_wuwa_banner}
                }
            }
        }
    }
} or nil,
'''
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'before'
match_indent = true
pattern = '''
if G.load_shop_booster then
'''
payload = '''
if G.GAME.mm_banner_slot then

    local banner_pool = {
        "p_mm_jinzhou_pack",
        "p_mm_rinascita_pack",
        "p_mm_blackshores_pack",
        "p_mm_lahairoi_pack"
    }

    local selection = pseudorandom_element(
        banner_pool,
        pseudoseed("mm_banner_shop")
    )

    local card = Card(
        G.shop_wuwa_banner.T.x +
        G.shop_wuwa_banner.T.w/2,
        G.shop_wuwa_banner.T.y,
        G.CARD_W + 0.5,
        G.CARD_H + 0.5,
        G.P_CARDS.empty,
        G.P_CENTERS[selection],
        {
            bypass_discovery_center = true,
            bypass_discovery_ui = true
        }
    )

    create_shop_card_ui(card)
    card:start_materialize()

    G.shop_wuwa_banner:emplace(card)
end
'''